include:
  - project: 'tmobile/templates'
    ref: tmo/master
    file: '/gitlab-ci/.tmo.global.common.gitlab-ci.yml'

  - project: 'tmobile/templates'
    ref:  tmo/master
    file: '/gitlab-ci/.tmo.function.docker.gitlab-ci.yml'

  - project: 'tmobile/templates'
    ref:  tmo/master
    file: 'gitlab-ci/.tmo.job.dockerScan.gitlab-ci.yml'

stages:
  - tmo
  - test
  - package
  - ci


package:
  stage: package
  extends: .docker-package
  variables:
    SOPS_VERSION: "v3.5.0"
    EXTRA_DOCKER_TAG: "$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHORT_SHA"
    DOCKER_BUILD_ARGS: "--build-arg VERSION=$SOPS_VERSION"

