#!/usr/bin/env bash

FILE=$1
OUTPUT="${FILE//.sops/}"

#Validate Inputs
if [ $# -lt 2 ]
then
 echo "Usage: $0 <filename> --rm" >&2
 exit 1
fi

# SOPS Decrypt
if ! [ -f "${1}" ];
then
  echo "!!! PASS FILENAME ONLY !!!" >&2
  exit 1
else
  echo "!!! DECRYPTING ${FILE} to ${OUTPUT}"
  sops --verbose --output "${OUTPUT}" --decrypt "${FILE}"
  rm "${FILE}"
  ls -la "${OUTPUT}"
fi