#!/usr/bin/env bash

while read KEY_VAR; do
  echo "### Importing GPG key from ${KEY_VAR}"
  echo "${!KEY_VAR}" | base64 -d | gpg --import
done < <(set -o posix; set | awk -F= -vRE="${1:-_KEY}" '$1 ~ RE { print $1 }')
